CREATE DATABASE CONTROL_USERS;

USE CONTROL_USERS;

CREATE TABLE IF NOT EXISTS 'persona' (
	'id' INT(3) PRIMARY KEY,
	'nombre' VARCHAR2(30) DEFAULT NULL,
	'edad' INT(3) DEFAULT NULL,
	'profesion' VARCHAR(30) DEFAULT NULL,
	'telefono' DECIMAL(10,0) DEFAULT NULL
);