package model;

public enum Type {

	/**
	 * PARA OPERACIONES QUE RETORNARÁ UN LISTADO: SELECTS.
	 */
	EXECUTE_QUERY,
	/**
	 * PARA OPERACIONES QUE RETORNARÁN UN ENTERO: INSERTS, UPDATE, DELETE
	 */
	EXECUTE_UPDATE
}
